export const BASE_URL = `https://tutorial-admin-dev-api.euron.live/api/v1`

export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNTFkZDAxLWRmNjYtNDUyYy1hZjMxLTI3YjBlYmMxZDcxMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcxNjAxNjk3OSwiZXhwIjoxNzE2MTAzMzc5fQ.MifIKuHKVeBdkUNhgepqd3IlGNcMpZC7iwmPl3b9Ea4'
