export const BASE_URL = `https://tutorial-admin-dev-api.euron.live/api/v1`

export const accessToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNTFkZDAxLWRmNjYtNDUyYy1hZjMxLTI3YjBlYmMxZDcxMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcxNjE5ODUyNywiZXhwIjoxNzE2Mjg0OTI3fQ.j7aE1O31Fu70q2RaM-Ajayd8keR0VSxVbyZ3Q6gvyCg'