export const BASE_URL = `https://tutorial-admin-dev-api.euron.live/api/v1`

export const accessToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNTFkZDAxLWRmNjYtNDUyYy1hZjMxLTI3YjBlYmMxZDcxMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcxNjE5NTY0MSwiZXhwIjoxNzE2MjgyMDQxfQ.2s7ZEVkPyiUPljqkaT0zXksxzf5XD5qDUXVrP48GhY8'