#!/usr/bin/env sh
. "$(dirname -- "$0")"

message="$(cat $1)"
requiredPattern="^(chore:|fix:|refactor:|optimise:|docs:|merge:|style:|add:|feat:|perf:|breaking_change:)+ .*issue: .*"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<verb in imperative mood>:<what was done> - issue: <issue id>"
  echo "Allowed verbs in imperative mood: chore:, fix:, refactor:, optimise:, docs:, merge:, style:, add:, feat:, perf:, breaking_change:"
  echo "Example: feat:add login button - issue: TB1-100"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  exit 1
fi
